In [49]:
import pandas as pd
import pandas_datareader.data as pdr
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib as plt
import plotly.express as px
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
plt.style.use('bmh')
import warnings
warnings.filterwarnings('ignore')

## VERİ HAKKINDA BİLGİ EDİNELİM VE EKSİK VERİ OLUP OLMADIGINI KONTROL EDELİM

In [4]:
df = pd.read_csv('dataset.csv')

In [5]:
df

CROP TYPE SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION  \
0       BANANA       DRY  DESERT       10-20            NORMAL   
1       BANANA       DRY  DESERT       10-20             SUNNY   
2       BANANA       DRY  DESERT       10-20             WINDY   
3       BANANA       DRY  DESERT       10-20             RAINY   
4       BANANA       DRY  DESERT       20-30            NORMAL   
...        ...       ...     ...         ...               ...   
2875     ONION       WET   HUMID       30-40             RAINY   
2876     ONION       WET   HUMID       40-50            NORMAL   
2877     ONION       WET   HUMID       40-50             SUNNY   
2878     ONION       WET   HUMID       40-50             WINDY   
2879     ONION       WET   HUMID       40-50             RAINY   

      WATER REQUIREMENT  
0                 8.750  
1                10.250  
2                 9.650  
3                 0.750  
4                 9.850  
...                 ...  
2875              0.100  
2876              4.625  
2877              6.125  
2878              5.625  
2879              0.200  

[2880 rows x 6 columns]

In [6]:
#Verimiz 2880 satır ve 6 sütündan oluşmaktadır.
df.columns

Index(['CROP TYPE', 'SOIL TYPE', 'REGION', 'TEMPERATURE', 'WEATHER CONDITION',
       'WATER REQUIREMENT'],
      dtype='object')

In [7]:
df.info() #Datasetimizde herhangi bir eksik veri yok.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CROP TYPE          2880 non-null   object 
 1   SOIL TYPE          2880 non-null   object 
 2   REGION             2880 non-null   object 
 3   TEMPERATURE        2880 non-null   object 
 4   WEATHER CONDITION  2880 non-null   object 
 5   WATER REQUIREMENT  2880 non-null   float64
dtypes: float64(1), object(5)
memory usage: 135.1+ KB


In [8]:
df.describe()

WATER REQUIREMENT
count        2880.000000
mean            6.463141
std            22.687385
min             0.100000
25%             2.700000
50%             5.860000
75%             8.000000
max           606.000000

In [9]:
df[df['WATER REQUIREMENT']==df['WATER REQUIREMENT'].max()]

CROP TYPE SOIL TYPE     REGION TEMPERATURE WEATHER CONDITION  \
1114     MELON       WET  SEMI ARID       30-40             WINDY   
1306     MAIZE       WET  SEMI ARID       30-40             WINDY   
2074   MUSTARD       WET  SEMI ARID       30-40             WINDY   
2650    TOMATO       WET  SEMI ARID       30-40             WINDY   

      WATER REQUIREMENT  
1114              606.0  
1306              606.0  
2074              606.0  
2650              606.0

In [10]:
df[df['WATER REQUIREMENT']==df['WATER REQUIREMENT'].min()]

CROP TYPE SOIL TYPE      REGION TEMPERATURE WEATHER CONDITION  \
35      BANANA       DRY  SEMI HUMID       10-20             RAINY   
51      BANANA       DRY       HUMID       10-20             RAINY   
83      BANANA     HUMID   SEMI ARID       10-20             RAINY   
99      BANANA     HUMID  SEMI HUMID       10-20             RAINY   
115     BANANA     HUMID       HUMID       10-20             RAINY   
...        ...       ...         ...         ...               ...   
2855     ONION       WET  SEMI HUMID       20-30            NORMAL   
2859     ONION       WET  SEMI HUMID       30-40            NORMAL   
2867     ONION       WET       HUMID       10-20            NORMAL   
2871     ONION       WET       HUMID       20-30             RAINY   
2875     ONION       WET       HUMID       30-40             RAINY   

      WATER REQUIREMENT  
35                  0.1  
51                  0.1  
83                  0.1  
99                  0.1  
115                 0.1  
...                 ...  
2855                0.1  
2859                0.1  
2867                0.1  
2871                0.1  
2875                0.1  

[157 rows x 6 columns]

## VERİ ÖNİŞLEME UYGULAMALARI

In [11]:
#VERİ SETİMİZDEKİ SICAKLIK DEGERLERİNİ ORTALAMA  DEGERLER İLE DEĞİŞTİRİP INT TÜRÜNE DÖNÜŞTÜREBİLİRİZ.
df['TEMPERATURE'] = df['TEMPERATURE'].replace(['10-20'],'15')
df['TEMPERATURE'] = df['TEMPERATURE'].replace(['20-30'],'25')
df['TEMPERATURE'] = df['TEMPERATURE'].replace(['30-40'],'35')
df['TEMPERATURE'] = df['TEMPERATURE'].replace(['40-50'],'45')  
df

CROP TYPE SOIL TYPE  REGION TEMPERATURE WEATHER CONDITION  \
0       BANANA       DRY  DESERT          15            NORMAL   
1       BANANA       DRY  DESERT          15             SUNNY   
2       BANANA       DRY  DESERT          15             WINDY   
3       BANANA       DRY  DESERT          15             RAINY   
4       BANANA       DRY  DESERT          25            NORMAL   
...        ...       ...     ...         ...               ...   
2875     ONION       WET   HUMID          35             RAINY   
2876     ONION       WET   HUMID          45            NORMAL   
2877     ONION       WET   HUMID          45             SUNNY   
2878     ONION       WET   HUMID          45             WINDY   
2879     ONION       WET   HUMID          45             RAINY   

      WATER REQUIREMENT  
0                 8.750  
1                10.250  
2                 9.650  
3                 0.750  
4                 9.850  
...                 ...  
2875              0.100  
2876              4.625  
2877              6.125  
2878              5.625  
2879              0.200  

[2880 rows x 6 columns]

In [12]:
df["TEMPERATURE"] = df.TEMPERATURE.astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CROP TYPE          2880 non-null   object 
 1   SOIL TYPE          2880 non-null   object 
 2   REGION             2880 non-null   object 
 3   TEMPERATURE        2880 non-null   int32  
 4   WEATHER CONDITION  2880 non-null   object 
 5   WATER REQUIREMENT  2880 non-null   float64
dtypes: float64(1), int32(1), object(4)
memory usage: 123.9+ KB


In [13]:
df_numeric = df[['TEMPERATURE', 'WATER REQUIREMENT']]
df_categorical = df[['CROP TYPE', 'SOIL TYPE', 'REGION', 'WEATHER CONDITION']]

In [14]:
df_numeric.head()

TEMPERATURE  WATER REQUIREMENT
0           15               8.75
1           15              10.25
2           15               9.65
3           15               0.75
4           25               9.85

In [15]:
df_categorical.head()

CROP TYPE SOIL TYPE  REGION WEATHER CONDITION
0    BANANA       DRY  DESERT            NORMAL
1    BANANA       DRY  DESERT             SUNNY
2    BANANA       DRY  DESERT             WINDY
3    BANANA       DRY  DESERT             RAINY
4    BANANA       DRY  DESERT            NORMAL

In [16]:
print(df['CROP TYPE'].unique())
print(df['SOIL TYPE'].unique())
print(df['REGION'].unique())
print(df['WEATHER CONDITION'].unique())

['BANANA' 'SOYABEAN' 'CABBAGE' 'POTATO' 'RICE' 'MELON' 'MAIZE' 'CITRUS'
 'BEAN' 'WHEAT' 'MUSTARD' 'COTTON' 'SUGARCANE' 'TOMATO' 'ONION']
['DRY' 'HUMID' 'WET']
['DESERT' 'SEMI ARID' 'SEMI HUMID' 'HUMID']
['NORMAL' 'SUNNY' 'WINDY' 'RAINY']


In [17]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
crop_encoder = OneHotEncoder()
crop_reshaped = np.array(df_categorical['CROP TYPE']).reshape(-1, 1)
crop_values = crop_encoder.fit_transform(crop_reshaped)

print(df_categorical['CROP TYPE'])
print()
print(crop_values.toarray())
print()
print(crop_encoder.inverse_transform(crop_values))

0       BANANA
1       BANANA
2       BANANA
3       BANANA
4       BANANA
         ...  
2875     ONION
2876     ONION
2877     ONION
2878     ONION
2879     ONION
Name: CROP TYPE, Length: 2880, dtype: object

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[['BANANA']
 ['BANANA']
 ['BANANA']
 ...
 ['ONION']
 ['ONION']
 ['ONION']]


In [18]:
soil_encoder = OneHotEncoder()
soil_reshaped = np.array(df_categorical['SOIL TYPE']).reshape(-1, 1)
soil_values = soil_encoder.fit_transform(soil_reshaped)
region_encoder = OneHotEncoder()
region_reshaped = np.array(df_categorical['REGION']).reshape(-1, 1)
region_values = region_encoder.fit_transform(region_reshaped)
weather_encoder = OneHotEncoder()
weather_reshaped = np.array(df_categorical['WEATHER CONDITION']).reshape(-1, 1)
weather_values = weather_encoder.fit_transform(weather_reshaped)

In [19]:
crop_type = pd.DataFrame(crop_values.toarray(), columns=
                        ['BANANA', 'SOYABEAN', 'CABBAGE', 'POTATO' ,'RICE' ,'MELON' ,'MAIZE' ,'CITRUS',
 'BEAN', 'WHEAT', 'MUSTARD' ,'COTTON', 'SUGARCANE' ,'TOMATO', 'ONION'])
soil_type = pd.DataFrame(soil_values.toarray(), columns=['DRY', 'HUMID' ,'WET'])
region_type = pd.DataFrame(region_values.toarray(), columns=['DESERT', 'SEMI ARID', 'SEMI HUMID', 'HUMID'])
weather_type = pd.DataFrame(weather_values.toarray(), columns=['NORMAL', 'SUNNY', 'WINDY', 'RAINY'])
df_categorical_encoded = pd.concat([crop_type, soil_type, region_type, weather_type], axis=1)
print(df_categorical_encoded.shape)
df_categorical_encoded.head()

(2880, 26)


BANANA  SOYABEAN  CABBAGE  POTATO  RICE  MELON  MAIZE  CITRUS  BEAN  WHEAT  \
0     1.0       0.0      0.0     0.0   0.0    0.0    0.0     0.0   0.0    0.0   
1     1.0       0.0      0.0     0.0   0.0    0.0    0.0     0.0   0.0    0.0   
2     1.0       0.0      0.0     0.0   0.0    0.0    0.0     0.0   0.0    0.0   
3     1.0       0.0      0.0     0.0   0.0    0.0    0.0     0.0   0.0    0.0   
4     1.0       0.0      0.0     0.0   0.0    0.0    0.0     0.0   0.0    0.0   

   ...  HUMID  WET  DESERT  SEMI ARID  SEMI HUMID  HUMID  NORMAL  SUNNY  \
0  ...    0.0  0.0     1.0        0.0         0.0    0.0     1.0    0.0   
1  ...    0.0  0.0     1.0        0.0         0.0    0.0     0.0    0.0   
2  ...    0.0  0.0     1.0        0.0         0.0    0.0     0.0    0.0   
3  ...    0.0  0.0     1.0        0.0         0.0    0.0     0.0    1.0   
4  ...    0.0  0.0     1.0        0.0         0.0    0.0     1.0    0.0   

   WINDY  RAINY  
0    0.0    0.0  
1    1.0    0.0  
2    0.0    1.0  
3    0.0    0.0  
4    0.0    0.0  

[5 rows x 26 columns]

In [20]:
df_new = pd.concat([df_numeric, df_categorical_encoded], axis=1)

In [21]:
df_new

TEMPERATURE  WATER REQUIREMENT  BANANA  SOYABEAN  CABBAGE  POTATO  RICE  \
0              15              8.750     1.0       0.0      0.0     0.0   0.0   
1              15             10.250     1.0       0.0      0.0     0.0   0.0   
2              15              9.650     1.0       0.0      0.0     0.0   0.0   
3              15              0.750     1.0       0.0      0.0     0.0   0.0   
4              25              9.850     1.0       0.0      0.0     0.0   0.0   
...           ...                ...     ...       ...      ...     ...   ...   
2875           35              0.100     0.0       0.0      0.0     0.0   0.0   
2876           45              4.625     0.0       0.0      0.0     0.0   0.0   
2877           45              6.125     0.0       0.0      0.0     0.0   0.0   
2878           45              5.625     0.0       0.0      0.0     0.0   0.0   
2879           45              0.200     0.0       0.0      0.0     0.0   0.0   

      MELON  MAIZE  CITRUS  ...  HUMID  WET  DESERT  SEMI ARID  SEMI HUMID  \
0       0.0    0.0     0.0  ...    0.0  0.0     1.0        0.0         0.0   
1       0.0    0.0     0.0  ...    0.0  0.0     1.0        0.0         0.0   
2       0.0    0.0     0.0  ...    0.0  0.0     1.0        0.0         0.0   
3       0.0    0.0     0.0  ...    0.0  0.0     1.0        0.0         0.0   
4       0.0    0.0     0.0  ...    0.0  0.0     1.0        0.0         0.0   
...     ...    ...     ...  ...    ...  ...     ...        ...         ...   
2875    0.0    0.0     0.0  ...    0.0  1.0     0.0        1.0         0.0   
2876    0.0    0.0     0.0  ...    0.0  1.0     0.0        1.0         0.0   
2877    0.0    0.0     0.0  ...    0.0  1.0     0.0        1.0         0.0   
2878    0.0    0.0     0.0  ...    0.0  1.0     0.0        1.0         0.0   
2879    0.0    0.0     0.0  ...    0.0  1.0     0.0        1.0         0.0   

      HUMID  NORMAL  SUNNY  WINDY  RAINY  
0       0.0     1.0    0.0    0.0    0.0  
1       0.0     0.0    0.0    1.0    0.0  
2       0.0     0.0    0.0    0.0    1.0  
3       0.0     0.0    1.0    0.0    0.0  
4       0.0     1.0    0.0    0.0    0.0  
...     ...     ...    ...    ...    ...  
2875    0.0     0.0    1.0    0.0    0.0  
2876    0.0     1.0    0.0    0.0    0.0  
2877    0.0     0.0    0.0    1.0    0.0  
2878    0.0     0.0    0.0    0.0    1.0  
2879    0.0     0.0    1.0    0.0    0.0  

[2880 rows x 28 columns]

In [22]:
print(df['WATER REQUIREMENT'].unique())

[8.750e+00 1.025e+01 9.650e+00 7.500e-01 9.850e+00 1.135e+01 1.075e+01
 8.500e-01 1.225e+01 1.165e+01 2.750e+00 1.175e+01 1.325e+01 1.265e+01
 3.750e+00 7.980e+00 9.400e+00 8.800e+00 2.500e-01 8.980e+00 1.040e+01
 9.700e+00 9.800e-01 9.980e+00 1.140e+01 1.080e+01 1.980e+00 1.090e+01
 1.240e+01 1.180e+01 2.700e+00 6.950e+00 8.450e+00 7.800e+00 1.000e-01
 7.950e+00 9.450e+00 5.000e-01 8.950e+00 1.045e+01 9.900e+00 9.500e-01
 1.900e+00 5.650e+00 7.150e+00 6.600e+00 8.100e+00 7.600e+00 3.000e-01
 7.680e+00 8.180e+00 8.600e+00 8.000e-01 8.650e+00 1.015e+01 6.500e-01
 6.695e+00 8.200e+00 7.700e+00 6.000e-01 7.695e+00 9.200e+00 8.700e+00
 1.020e+01 9.600e+00 7.000e-01 9.500e+00 1.100e+01 1.050e+01 1.500e+00
 5.920e+00 7.420e+00 6.900e+00 6.920e+00 8.420e+00 7.900e+00 7.920e+00
 9.420e+00 8.900e+00 8.920e+00 1.042e+01 9.200e-01 4.890e+00 6.390e+00
 5.800e+00 5.600e+00 7.100e+00 2.000e-01 6.500e+00 7.500e+00 9.000e+00
 8.500e+00 3.650e+00 5.150e+00 4.650e+00 6.150e+00 5.000e+00 6.000e+00
 6.650

In [23]:
su_ihtiyaci = df_new["WATER REQUIREMENT"].values
katagori = []
for num in su_ihtiyaci:
    if num < 1:
        katagori.append("1'den az")
    elif num > 1 and num < 3 :
        katagori.append("1 ile 3 arasi")
    elif num > 3 and num < 6 :
        katagori.append("3 ile 6 arasi")
    elif num > 6 and num < 9 :
        katagori.append("6 ile 9 arasi")
    elif num > 9 and num < 12 :
        katagori.append("9 ile 12 arasi")
    else:
        katagori.append("12'den cok")
katagori = pd.DataFrame(data=katagori, columns=["Katagori"])
data = pd.concat([df_new, katagori], axis=1)
data.drop(columns="WATER REQUIREMENT", axis=1, inplace=True)

In [24]:
data

TEMPERATURE  BANANA  SOYABEAN  CABBAGE  POTATO  RICE  MELON  MAIZE  \
0              15     1.0       0.0      0.0     0.0   0.0    0.0    0.0   
1              15     1.0       0.0      0.0     0.0   0.0    0.0    0.0   
2              15     1.0       0.0      0.0     0.0   0.0    0.0    0.0   
3              15     1.0       0.0      0.0     0.0   0.0    0.0    0.0   
4              25     1.0       0.0      0.0     0.0   0.0    0.0    0.0   
...           ...     ...       ...      ...     ...   ...    ...    ...   
2875           35     0.0       0.0      0.0     0.0   0.0    0.0    0.0   
2876           45     0.0       0.0      0.0     0.0   0.0    0.0    0.0   
2877           45     0.0       0.0      0.0     0.0   0.0    0.0    0.0   
2878           45     0.0       0.0      0.0     0.0   0.0    0.0    0.0   
2879           45     0.0       0.0      0.0     0.0   0.0    0.0    0.0   

      CITRUS  BEAN  ...  WET  DESERT  SEMI ARID  SEMI HUMID  HUMID  NORMAL  \
0        0.0   0.0  ...  0.0     1.0        0.0         0.0    0.0     1.0   
1        0.0   0.0  ...  0.0     1.0        0.0         0.0    0.0     0.0   
2        0.0   0.0  ...  0.0     1.0        0.0         0.0    0.0     0.0   
3        0.0   0.0  ...  0.0     1.0        0.0         0.0    0.0     0.0   
4        0.0   0.0  ...  0.0     1.0        0.0         0.0    0.0     1.0   
...      ...   ...  ...  ...     ...        ...         ...    ...     ...   
2875     0.0   1.0  ...  1.0     0.0        1.0         0.0    0.0     0.0   
2876     0.0   1.0  ...  1.0     0.0        1.0         0.0    0.0     1.0   
2877     0.0   1.0  ...  1.0     0.0        1.0         0.0    0.0     0.0   
2878     0.0   1.0  ...  1.0     0.0        1.0         0.0    0.0     0.0   
2879     0.0   1.0  ...  1.0     0.0        1.0         0.0    0.0     0.0   

      SUNNY  WINDY  RAINY        Katagori  
0       0.0    0.0    0.0   6 ile 9 arasi  
1       0.0    1.0    0.0  9 ile 12 arasi  
2       0.0    0.0    1.0  9 ile 12 arasi  
3       1.0    0.0    0.0        1'den az  
4       0.0    0.0    0.0  9 ile 12 arasi  
...     ...    ...    ...             ...  
2875    1.0    0.0    0.0        1'den az  
2876    0.0    0.0    0.0   3 ile 6 arasi  
2877    0.0    1.0    0.0   6 ile 9 arasi  
2878    0.0    0.0    1.0   3 ile 6 arasi  
2879    1.0    0.0    0.0        1'den az  

[2880 rows x 28 columns]

In [25]:
print(data['Katagori'].unique())

['6 ile 9 arasi' '9 ile 12 arasi' "1'den az" "12'den cok" '1 ile 3 arasi'
 '3 ile 6 arasi']


In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2880 entries, 0 to 2879
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   TEMPERATURE  2880 non-null   int32  
 1   BANANA       2880 non-null   float64
 2   SOYABEAN     2880 non-null   float64
 3   CABBAGE      2880 non-null   float64
 4   POTATO       2880 non-null   float64
 5   RICE         2880 non-null   float64
 6   MELON        2880 non-null   float64
 7   MAIZE        2880 non-null   float64
 8   CITRUS       2880 non-null   float64
 9   BEAN         2880 non-null   float64
 10  WHEAT        2880 non-null   float64
 11  MUSTARD      2880 non-null   float64
 12  COTTON       2880 non-null   float64
 13  SUGARCANE    2880 non-null   float64
 14  TOMATO       2880 non-null   float64
 15  ONION        2880 non-null   float64
 16  DRY          2880 non-null   float64
 17  HUMID        2880 non-null   float64
 18  WET          2880 non-null   float64
 19  DESERT

In [27]:
data.to_csv('sonhali4.csv')

## Veri Setini Ayırma

In [28]:
from sklearn.model_selection import train_test_split

col_isimler = ['TEMPERATURE', 'BANANA', 'SOYABEAN', 'CABBAGE',
                     'POTATO','RICE','MELON','MAIZE','CITRUS','BEAN','WHEAT','MUSTARD','COTTON',
              'SUGARCANE','TOMATO','ONION','DRY','HUMID','WET','DESERT','SEMI ARID','SEMI HUMID','HUMID',
             'NORMAL','SUNNY','WINDY','RAINY' ]
tahmin_isimler = ['Katagori']

X = data[col_isimler].values 

y = data[tahmin_isimler].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2018) 

## Model Oluşturma

## Naive bayes

In [29]:
from sklearn.naive_bayes import GaussianNB


nb_model = GaussianNB()

nb_model.fit(X_train, y_train.ravel())

GaussianNB()

In [33]:
prediction_from_trained_data = nb_model.predict(X_train)
accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Naive Bayes ile eğitim başarısı : {0:.4f}".format(accuracy))

Naive Bayes ile eğitim başarısı : 0.5638


In [34]:
nb_predict_test = nb_model.predict(X_test)
print(classification_report(y_test, nb_predict_test))
print("Naive Bayesin test verisi üzerinde'ki performansı %s" %
      accuracy_score(y_test, nb_predict_test))

                precision    recall  f1-score   support

 1 ile 3 arasi       0.00      0.00      0.00        19
      1'den az       0.90      0.90      0.90       126
    12'den cok       0.50      0.47      0.48        47
 3 ile 6 arasi       0.62      0.55      0.59       146
 6 ile 9 arasi       0.64      0.22      0.33       186
9 ile 12 arasi       0.19      0.77      0.31        52

      accuracy                           0.52       576
     macro avg       0.48      0.48      0.43       576
  weighted avg       0.62      0.52      0.52       576

Naive Bayesin test verisi üzerinde'ki performansı 0.515625


In [35]:
print ("Naive Bayes için Karışıklık matrisi ")


print ("{0}".format(metrics.confusion_matrix(y_test, nb_predict_test,
                                             
                                             labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

print ("")

print ("Sınıflandırma Raporu\n")


print ("{0}".format(metrics.classification_report(y_test, nb_predict_test, labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

Naive Bayes için Karışıklık matrisi 
[[ 41 110   1  10   0  24]
 [  4  40   0   8   0   0]
 [  0   0 113   1   5   7]
 [  2  16   0  22   0   7]
 [  0   1   6   1   0  11]
 [ 17  40   5   2   1  81]]

Sınıflandırma Raporu

                precision    recall  f1-score   support

 6 ile 9 arasi       0.64      0.22      0.33       186
9 ile 12 arasi       0.19      0.77      0.31        52
      1'den az       0.90      0.90      0.90       126
    12'den cok       0.50      0.47      0.48        47
 1 ile 3 arasi       0.00      0.00      0.00        19
 3 ile 6 arasi       0.62      0.55      0.59       146

      accuracy                           0.52       576
     macro avg       0.48      0.48      0.43       576
  weighted avg       0.62      0.52      0.52       576



## Destek Vektör Makineleri

In [37]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear', C=1, random_state=42)

svm_model.fit(X_train, y_train.ravel())

SVC(C=1, kernel='linear', random_state=42)

In [38]:
prediction_from_trained_data = svm_model.predict(X_train)
accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Destek Vektör Makineleri ile eğitim başarısı : {0:.4f}".format(accuracy))

Destek Vektör Makineleri ile eğitim başarısı : 0.8273


In [39]:
svm_predict_test = svm_model.predict(X_test)
print(classification_report(y_test, svm_predict_test))
print("Destek Vektör Makinalarının test verisi üzerinde performansı %s" %
      accuracy_score(y_test, svm_predict_test))

                precision    recall  f1-score   support

 1 ile 3 arasi       0.33      0.05      0.09        19
      1'den az       0.91      0.94      0.92       126
    12'den cok       0.66      0.49      0.56        47
 3 ile 6 arasi       0.79      0.93      0.86       146
 6 ile 9 arasi       0.90      0.88      0.89       186
9 ile 12 arasi       0.72      0.75      0.74        52

      accuracy                           0.84       576
     macro avg       0.72      0.67      0.68       576
  weighted avg       0.82      0.84      0.82       576

Destek Vektör Makinalarının test verisi üzerinde performansı 0.8350694444444444


In [40]:
print ("Destek Vektör Makinaları için Karışıklık matrisi ")


print ("{0}".format(metrics.confusion_matrix(y_test, svm_predict_test,
                                             
                                             labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

print ("")

print ("Sınıflandırma Raporu\n")


print ("{0}".format(metrics.classification_report(y_test, svm_predict_test, labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

Destek Vektör Makinaları için Karışıklık matrisi 
[[164   5   1   3   0  13]
 [  4  39   0   9   0   0]
 [  1   0 118   0   1   6]
 [  8  10   0  23   1   5]
 [  0   0   6   0   1  12]
 [  5   0   5   0   0 136]]

Sınıflandırma Raporu

                precision    recall  f1-score   support

 6 ile 9 arasi       0.90      0.88      0.89       186
9 ile 12 arasi       0.72      0.75      0.74        52
      1'den az       0.91      0.94      0.92       126
    12'den cok       0.66      0.49      0.56        47
 1 ile 3 arasi       0.33      0.05      0.09        19
 3 ile 6 arasi       0.79      0.93      0.86       146

      accuracy                           0.84       576
     macro avg       0.72      0.67      0.68       576
  weighted avg       0.82      0.84      0.82       576



## Karar Ağaçları

In [41]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train.ravel())

DecisionTreeClassifier(random_state=42)

In [42]:
prediction_from_trained_data = dt_model.predict(X_train)
accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Karar ağaçları ile eğitim başarısı : {0:.4f}".format(accuracy))

Karar ağaçları ile eğitim başarısı : 0.9987


In [43]:
dt_predict_test = dt_model.predict(X_test)

print(classification_report(y_test, dt_predict_test))
print("Karar Ağaçlarının test verisi üzerinde'ki performansı %s" %
      accuracy_score(y_test, dt_predict_test))

                precision    recall  f1-score   support

 1 ile 3 arasi       0.44      0.58      0.50        19
      1'den az       0.93      0.94      0.94       126
    12'den cok       0.59      0.47      0.52        47
 3 ile 6 arasi       0.77      0.75      0.76       146
 6 ile 9 arasi       0.80      0.77      0.78       186
9 ile 12 arasi       0.59      0.73      0.66        52

      accuracy                           0.77       576
     macro avg       0.69      0.71      0.69       576
  weighted avg       0.77      0.77      0.77       576

Karar Ağaçlarının test verisi üzerinde'ki performansı 0.7690972222222222


In [44]:
print ("Karar Ağaçları için Karışıklık matrisi ")


print ("{0}".format(metrics.confusion_matrix(y_test, dt_predict_test,
                                             
                                             labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

print ("")

print ("Sınıflandırma Raporu\n")


print ("{0}".format(metrics.classification_report(y_test, dt_predict_test, labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

Karar Ağaçları için Karışıklık matrisi 
[[144  13   1   8   0  20]
 [  9  38   0   5   0   0]
 [  1   0 119   0   1   5]
 [  7  13   0  22   2   3]
 [  0   0   4   0  11   4]
 [ 20   0   4   2  11 109]]

Sınıflandırma Raporu

                precision    recall  f1-score   support

 6 ile 9 arasi       0.80      0.77      0.78       186
9 ile 12 arasi       0.59      0.73      0.66        52
      1'den az       0.93      0.94      0.94       126
    12'den cok       0.59      0.47      0.52        47
 1 ile 3 arasi       0.44      0.58      0.50        19
 3 ile 6 arasi       0.77      0.75      0.76       146

      accuracy                           0.77       576
     macro avg       0.69      0.71      0.69       576
  weighted avg       0.77      0.77      0.77       576



## Yapay Sinir Ağları

In [46]:
ann_model = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500, random_state=42)
ann_model.fit(X_train, y_train.ravel())

MLPClassifier(hidden_layer_sizes=(13, 13, 13), max_iter=500, random_state=42)

In [47]:
prediction_from_trained_data = ann_model.predict(X_train)
accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Yapay Sinir Ağları ile eğitim başarısı : {0:.4f}".format(accuracy))

Yapay Sinir Ağları ile eğitim başarısı : 0.9210


In [48]:
ann_predict_test = ann_model.predict(X_test)

print(classification_report(y_test, ann_predict_test))
print("Yapay Sinir Ağlarının test verisi üzerinde'ki performansı %s" %
      accuracy_score(y_test, ann_predict_test))

                precision    recall  f1-score   support

 1 ile 3 arasi       0.74      0.74      0.74        19
      1'den az       0.95      0.94      0.94       126
    12'den cok       0.81      0.64      0.71        47
 3 ile 6 arasi       0.86      0.95      0.90       146
 6 ile 9 arasi       0.94      0.92      0.93       186
9 ile 12 arasi       0.79      0.81      0.80        52

      accuracy                           0.89       576
     macro avg       0.85      0.83      0.84       576
  weighted avg       0.89      0.89      0.89       576

Yapay Sinir Ağlarının test verisi üzerinde'ki performansı 0.890625


In [50]:
print ("Yapay Sinir Ağları için karışıklık matrisi")


print ("{0}".format(metrics.confusion_matrix(y_test, ann_predict_test,
                                             
                                             labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

print ("")

print ("Sınıflandırma Raporu\n")


print ("{0}".format(metrics.classification_report(y_test, ann_predict_test, labels=['6 ile 9 arasi',
 '9 ile 12 arasi',
 "1'den az",
 "12'den cok",
 '1 ile 3 arasi',
 '3 ile 6 arasi'])))

Yapay Sinir Ağları için karışıklık matrisi
[[171   6   1   1   0   7]
 [  4  42   0   6   0   0]
 [  0   0 118   0   2   6]
 [  4   5   1  30   0   7]
 [  0   0   2   0  14   3]
 [  3   0   2   0   3 138]]

Sınıflandırma Raporu

                precision    recall  f1-score   support

 6 ile 9 arasi       0.94      0.92      0.93       186
9 ile 12 arasi       0.79      0.81      0.80        52
      1'den az       0.95      0.94      0.94       126
    12'den cok       0.81      0.64      0.71        47
 1 ile 3 arasi       0.74      0.74      0.74        19
 3 ile 6 arasi       0.86      0.95      0.90       146

      accuracy                           0.89       576
     macro avg       0.85      0.83      0.84       576
  weighted avg       0.89      0.89      0.89       576

